### ISSUE TITLE
Install Python 3.7.9 and Django to the server

### ISSUE THREAD

**Issue by Criyl** [esucsowt/website#14]
In order to start work on the Django backend we need
Python 3.7.9 
Django 
Anaconda (optional)

**Comment by Criyl** [comment]
Anaconda would be another good addition.

**Comment by Criyl** [comment]
This may be useful.
https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/

**Comment by tona1337** [comment]
Both have been installed and tested.
