### ISSUE TITLE
Get git repo linked

### ISSUE THREAD

**Issue by RyanSpadt** [esucsowt/website#15]
Get git repo linked to the server being used in live production. We should also have a separate branch that changes get merged too first and can be tested before merging to the live branch.

**Comment by RyanSpadt** [comment]
We will want to do this inside the Django Virtual Environment.

**Comment by Criyl** [comment]
We can use the main branch as a live branch and have a dev branch that represents the W.I.P

**Comment by tona1337** [comment]
Wrote a bash script for automatically pulling the main branch to server, updating and restarting all necessary modules. This script has been tested and is successfully working.
