### ISSUE TITLE
Back-to-Top button on all pages

### ISSUE THREAD

**Issue by Rocksnotch** [esucsowt/website#24]
Just having a button to bring you back to the top of the page. Might be more of a Quality-of-Life feature than anything, but still something nice to have.

**Comment by Criyl** [comment]
Would be nice if it slowly scrolled up rather than just jumped to the top as well.

**Comment by PaigesterM** [comment]
> Would be nice if it slowly scrolled up rather than just jumped to the top as well.

rip but it's so easy to just jump to the top

**Comment by Rocksnotch** [comment]
> > Would be nice if it slowly scrolled up rather than just jumped to the top as well.
> 
> rip but it's so easy to just jump to the top

its VERY easy to have it just jump to the top, but it can't be that much harder to have it scroll can it?

**Comment by Criyl** [comment]
Since we're using bootstrap it should be pretty easy. [snippet](https://bootsnipp.com/snippets/PE41m)

**Comment by RyanSpadt** [comment]
Smooth scroll to top added #61
