### ISSUE TITLE
add django installation/additional local setup to readme

### ISSUE THREAD

**Issue by johnwinward** [esucsowt/website#30]
Since we added a backend, it may be more confusing for new contributors to test changes they make or see a local site before creating a pull request. Contributors who are completely new may need quick guide for installing django and running a local project. We could add a section to the readme for this.

**Comment by Criyl** [comment]
We are starting work on our [wiki](https://github.com/esucsowt/website/wiki/Setting-up-your-development-environment) to provide that information, if anyone wishes to build the project on dev they can use the 
`pip install -r requirements.txt` 
command at the root of our repo
