### ISSUE TITLE
Decide on a Backend

### ISSUE THREAD

**Issue by Criyl** [esucsowt/website#5]
the title says it all

**Comment by Criyl** [comment]
Django is one option, it is in python a rather easy to use language and seems fairly modern.

**Comment by RyanSpadt** [comment]
Django is the most popular Python web framework on the market right now. It would allow users to gain valuable experience in a widely used tool. It is also well documented, highly secure, and easy to pick up for future web teams to learn and use.

**Comment by Criyl** [comment]
We should decide this soon, I say we move to just use Django since I don't see any suggested alternatives.

**Comment by Criyl** [comment]
## Backend Poll
[![](https://api.gh-polls.com/poll/01EYKKJKYTPVYJDBN8V9TD4YJA/Django)](https://api.gh-polls.com/poll/01EYKKJKYTPVYJDBN8V9TD4YJA/Django/vote)
[![](https://api.gh-polls.com/poll/01EYKKJKYTPVYJDBN8V9TD4YJA/Some%20other%20thing%20(Comment%20framework))](https://api.gh-polls.com/poll/01EYKKJKYTPVYJDBN8V9TD4YJA/Some%20other%20thing%20(Comment%20framework)/vote)

**Comment by PaigesterM** [comment]
I would also be fine with Php, but I agree it's important to use more common tools so if anyone runs into it later they already have experience with it.

**Comment by tona1337** [comment]
I'm fine with anything. Would like to learn PHP but Django looks promising as well.

**Comment by Criyl** [comment]
Verdict! Django it is! Start planning tickets for the different segments for the backend, if we can break it into separate modules that would be best.
