### ISSUE TITLE
Make Detailed Readme

### ISSUE THREAD

**Issue by RyanSpadt** [esucsowt/website#9]
Create ReadMe File for Project with current status and necessary information. Also Include short demonstration of project with media.

**Comment by Criyl** [comment]
What kind of information should be on the Readme?

**Comment by RyanSpadt** [comment]
Preferrably in this order:

What is the project trying to achieve?
What are the requirements to using it?
How do I set up the requirements to use it?
How can I join?
Followed by current known bugs and maybe latest additions/what's being worked on

Of course including media as well.
